workflows:
  flutter-workflow:
    name: Flutter Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          cd milk
          flutter pub get

      - name: Build APK
        script: |
          cd milk
          flutter build apk --release

      - name: Build iOS
        script: |
          cd milk
          flutter build ios --release --no-codesign

    artifacts:
      - milk/build/app/outputs/flutter-apk/app-release.apk
      - milk/build/ios/iphoneos/*.app
