// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-vGxSwqDAzgHA5pOrNSmBA2E4DM0FSuw',
    appId: '1:128871979781:web:11765da1820befb7c3356c',
    messagingSenderId: '128871979781',
    projectId: 'milk-df041',
    authDomain: 'milk-df041.firebaseapp.com',
    databaseURL: 'https://milk-df041-default-rtdb.firebaseio.com',
    storageBucket: 'milk-df041.firebasestorage.app',
    measurementId: 'G-W0KJZQELF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGnu8TnpENTEJezbrDVZItUbuHhcYiK9k',
    appId: '1:128871979781:android:faf19d66ef251cd6c3356c',
    messagingSenderId: '128871979781',
    projectId: 'milk-df041',
    databaseURL: 'https://milk-df041-default-rtdb.firebaseio.com',
    storageBucket: 'milk-df041.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuMN_gU4emCN_F5kyB0QrNyURMzm9GdSE',
    appId: '1:128871979781:ios:46addb7da2853e21c3356c',
    messagingSenderId: '128871979781',
    projectId: 'milk-df041',
    databaseURL: 'https://milk-df041-default-rtdb.firebaseio.com',
    storageBucket: 'milk-df041.firebasestorage.app',
    iosBundleId: 'com.example.milk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuMN_gU4emCN_F5kyB0QrNyURMzm9GdSE',
    appId: '1:128871979781:ios:46addb7da2853e21c3356c',
    messagingSenderId: '128871979781',
    projectId: 'milk-df041',
    databaseURL: 'https://milk-df041-default-rtdb.firebaseio.com',
    storageBucket: 'milk-df041.firebasestorage.app',
    iosBundleId: 'com.example.milk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-vGxSwqDAzgHA5pOrNSmBA2E4DM0FSuw',
    appId: '1:128871979781:web:fcaaa7361e3b449cc3356c',
    messagingSenderId: '128871979781',
    projectId: 'milk-df041',
    authDomain: 'milk-df041.firebaseapp.com',
    databaseURL: 'https://milk-df041-default-rtdb.firebaseio.com',
    storageBucket: 'milk-df041.firebasestorage.app',
    measurementId: 'G-9C4V808XF2',
  );
}
